
matrix:
  fast_finish: true
  sudo: true
  include:
    - language: c
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - make clean all
    - language: c
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - make clean test
